/*
# Add document upload support to courses

1. Modified Tables
- `courses`: add `document_path` (text, nullable) — storage path of the uploaded document
  and `document_name` (text, nullable) — original filename for display.
  The existing `documentation` text column is kept for backward compatibility but
  will no longer be used by the UI.

2. Storage
- Create a private storage bucket `course-documents` for uploaded course documents.
- Policies:
  - formateurs and admins can upload (INSERT) to the bucket
  - formateurs and admins can delete files they own
  - authenticated users can read files (for signed URL generation)
  - No public access — files are only accessible via signed URLs generated by the app

3. Security
- The bucket is private, so files cannot be accessed via public URLs.
- Students access documents only through signed URLs generated in-app, displayed
  in an embedded viewer without download controls.
*/

ALTER TABLE courses
  ADD COLUMN IF NOT EXISTS document_path text,
  ADD COLUMN IF NOT EXISTS document_name text;

-- Create the storage bucket (private)
INSERT INTO storage.buckets (id, name, public)
VALUES ('course-documents', 'course-documents', false)
ON CONFLICT (id) DO NOTHING;

-- Policies for the storage bucket
-- Allow authenticated users to read (needed for signed URLs)
DROP POLICY IF EXISTS "course_docs_read" ON storage.objects;
CREATE POLICY "course_docs_read"
ON storage.objects FOR SELECT
TO authenticated
USING (bucket_id = 'course-documents');

-- Allow formateurs and admins to upload
DROP POLICY IF EXISTS "course_docs_upload" ON storage.objects;
CREATE POLICY "course_docs_upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'course-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role IN ('formateur', 'admin')
  )
);

-- Allow formateurs and admins to update (overwrite)
DROP POLICY IF EXISTS "course_docs_update" ON storage.objects;
CREATE POLICY "course_docs_update"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'course-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role IN ('formateur', 'admin')
  )
)
WITH CHECK (
  bucket_id = 'course-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role IN ('formateur', 'admin')
  )
);

-- Allow formateurs and admins to delete
DROP POLICY IF EXISTS "course_docs_delete" ON storage.objects;
CREATE POLICY "course_docs_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'course-documents'
  AND EXISTS (
    SELECT 1 FROM profiles
    WHERE profiles.id = auth.uid()
    AND profiles.role IN ('formateur', 'admin')
  )
);
