/*
# Add n8n session flag support

## Context
The n8n workflows generate a unique flag per VM session (not from the flags table).
When n8n provisions a VM, it returns { session_id, access_url, flag, expires_at }.
The app needs to store this flag on the activity_session and verify it separately
from the static flags table.

## Changes
1. activity_sessions: add `n8n_session_id` (text) — the session ID returned by n8n
2. activity_sessions: add `n8n_flag` (text) — the unique flag generated by n8n for this session
3. activity_sessions: add `n8n_flag_solved` (boolean, default false) — whether the student found the n8n flag
4. New RPC `verify_session_flag(p_session_id, p_submitted_value)` — SECURITY DEFINER function
   that checks the submitted value against n8n_flag, marks solved, awards points to flag_submissions,
   and returns a result struct compatible with verify_flag.

## Security
- verify_session_flag is SECURITY DEFINER so it can read n8n_flag (which the student must never see directly).
- It verifies the session belongs to the calling student via auth.uid().
- RLS already protects activity_sessions; the new columns are covered by existing policies.
*/

-- Add columns to activity_sessions
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'activity_sessions' AND column_name = 'n8n_session_id') THEN
    ALTER TABLE activity_sessions ADD COLUMN n8n_session_id text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'activity_sessions' AND column_name = 'n8n_flag') THEN
    ALTER TABLE activity_sessions ADD COLUMN n8n_flag text;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'activity_sessions' AND column_name = 'n8n_flag_solved') THEN
    ALTER TABLE activity_sessions ADD COLUMN n8n_flag_solved boolean DEFAULT false;
  END IF;
END $$;

-- verify_session_flag: checks student's submitted flag against the n8n-generated flag
CREATE OR REPLACE FUNCTION verify_session_flag(p_session_id uuid, p_submitted_value text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session activity_sessions%ROWTYPE;
  v_correct boolean;
  v_already_solved boolean;
  v_points integer;
  v_lab_id uuid;
BEGIN
  -- Load the session
  SELECT * INTO v_session FROM activity_sessions WHERE id = p_session_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'correct', false, 'points', 0, 'message', 'Session introuvable', 'error', 'not_found');
  END IF;

  -- Verify ownership
  IF v_session.student_id <> auth.uid() THEN
    RETURN jsonb_build_object('success', false, 'correct', false, 'points', 0, 'message', 'Accès refusé', 'error', 'forbidden');
  END IF;

  -- Must have an n8n flag
  IF v_session.n8n_flag IS NULL THEN
    RETURN jsonb_build_object('success', false, 'correct', false, 'points', 0, 'message', 'Aucun flag pour cette session', 'error', 'no_flag');
  END IF;

  v_already_solved := v_session.n8n_flag_solved;
  v_correct := (trim(p_submitted_value) = trim(v_session.n8n_flag));
  v_lab_id := v_session.lab_id;
  v_points := 100; -- default points for n8n session flag

  IF v_correct AND NOT v_already_solved THEN
    -- Mark as solved
    UPDATE activity_sessions SET n8n_flag_solved = true WHERE id = p_session_id;

    -- Award points via flag_submissions (link to first flag of the lab if exists, else null)
    INSERT INTO flag_submissions (student_id, flag_id, submitted_value, is_correct, points_awarded)
    SELECT v_session.student_id, f.id, p_submitted_value, true, v_points
    FROM flags f
    WHERE f.lab_id = v_lab_id
    ORDER BY f.sort_order
    LIMIT 1;

    -- If no flags exist for this lab, insert with null flag_id
    IF NOT FOUND THEN
      INSERT INTO flag_submissions (student_id, flag_id, submitted_value, is_correct, points_awarded)
      VALUES (v_session.student_id, NULL, p_submitted_value, true, v_points);
    END IF;

    RETURN jsonb_build_object('success', true, 'correct', true, 'points', v_points, 'message', 'Flag validé ! Bien joué.', 'already_solved', false);
  ELSIF v_correct AND v_already_solved THEN
    RETURN jsonb_build_object('success', true, 'correct', true, 'points', v_points, 'message', 'Flag déjà validé', 'already_solved', true);
  ELSE
    -- Record incorrect attempt
    INSERT INTO flag_submissions (student_id, flag_id, submitted_value, is_correct, points_awarded)
    SELECT v_session.student_id, f.id, p_submitted_value, false, 0
    FROM flags f
    WHERE f.lab_id = v_lab_id
    ORDER BY f.sort_order
    LIMIT 1;

    IF NOT FOUND THEN
      INSERT INTO flag_submissions (student_id, flag_id, submitted_value, is_correct, points_awarded)
      VALUES (v_session.student_id, NULL, p_submitted_value, false, 0);
    END IF;

    RETURN jsonb_build_object('success', true, 'correct', false, 'points', 0, 'message', 'Flag incorrect. Réessayez.');
  END IF;
END;
$$;

-- Grant execute to authenticated
GRANT EXECUTE ON FUNCTION verify_session_flag(uuid, text) TO authenticated;
